### ISSUE TITLE
Upgrade 2.7.0.beta8 -> 2.8.0.beta2 fails

### ISSUE THREAD

**Issue by mrloop** [mrloop/garmin_connect_onebox#2]
https://meta.discourse.org/t/upgrade-2-7-0-beta8-2-8-0-beta2-failed-rebuild-failed/194636

```
I, [2021-06-22T05:54:52.584458 #1776]  INFO -- : Refreshing Gem list
** PLUGIN FAILURE **

You are unable to build Discourse due to this error during plugin
initialization:

uninitialized constant Onebox

/var/www/discourse/plugins/garmin_connect_onebox/plugin.rb:6:in `activate!'
/var/www/discourse/lib/plugin/instance.rb:622:in `instance_eval'
/var/www/discourse/lib/plugin/instance.rb:622:in `activate!'
lib/discourse.rb:240:in `block in activate_plugins!'
lib/discourse.rb:237:in `each'
lib/discourse.rb:237:in `activate_plugins!'
/var/www/discourse/config/application.rb:313:in `block in <class:Application>'
/var/www/discourse/lib/plugin_initialization_guard.rb:5:in `plugin_initialization_guard'
/var/www/discourse/config/application.rb:312:in `<class:Application>'
/var/www/discourse/config/application.rb:73:in `<module:Discourse>'
/var/www/discourse/config/application.rb:72:in `<top (required)>'
/var/www/discourse/config/environment.rb:4:in `require'
/var/www/discourse/config/environment.rb:4:in `<top (required)>'
config.ru:7:in `require'
config.ru:7:in `block in <main>'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.0.0/lib/unicorn.rb:54:in `eval'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.0.0/lib/unicorn.rb:54:in `block in builder'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:826:in `build_app!'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.0.0/lib/unicorn/http_server.rb:140:in `start'
/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/unicorn-6.0.0/bin/unicorn:128:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.7.0/bin/unicorn:23:in `load'
/var/www/discourse/vendor/bundle/ruby/2.7.0/bin/unicorn:23:in `<main>'
```

**Comment by Alan-Liang** [comment]
Same problem here, it seems that the commit "[DEV: Absorb onebox gem into core](https://github.com/discourse/discourse/commit/283b08d45f28236e32f682d1b531520682c0b440)" changed the order of evaluation, and adding this line fixes the problem:

<https://github.com/acm-21/discourse-onebox-bilibili/blob/ffcc3f6fc1fc87e2e494754afddd294883aa6ad7/plugin.rb#L7>

Disclaimer: I'm totally new to Ruby, so even myself doesn't know what exactly I'm doing.

**Comment by mrloop** [comment]
:tada: thanks @Alan-Liang
